### PR TITLE
Rename TokenType Operators

### PR DESCRIPTION
**Pull request by Superstar64**
Better naming for some of the TokenType Operators

### CODE REVIEW

**Comment by deadalnix** [comment]
Keep trailing comas. Also, does with(): works ? That would be clearer.

**Comment by Superstar64** [comment]
"with():" does not work.
src/d/lexer.d(870): Error: found ':' instead of statement
src/d/lexer.d(939): Error: found ':' instead of statement

**Comment by deadalnix** [comment]
Maybe it is worth filling a bug report.

**Comment by deadalnix** [comment]
Ok put the with on the line before the return and mention why in the comment. Please refers to:
https://issues.dlang.org/show_bug.cgi?id=14332

Also, please keep trailing coma.

**Comment by Superstar64** [comment]
I already readded trailing commas, here https://github.com/Superstar64/libd/commit/dcfbbb5137035cb378e5b182f01232a51a2df717 or did you mean something else.

**Comment by deadalnix** [comment]
Ok cool, this is in shape. Please make it so that there is only one commit, and then I'm going to merge.

**Comment by Superstar64** [comment]
Ok, commits squashed.

**Comment by deadalnix** [comment]
Thank you :)

**Comment by schancel** [comment]
@Superstar64 We have a slack channel for people working on libd -- if you provide me with some contact info I can sent you an invite.  It is a nice way for us to all sync up and work on things.

**Comment by deadalnix** [comment]
Thumb up :)

**Comment by Superstar64** [comment]
@schancel No thanks, I'm not sure whether I am going to be a long term contributor or not.

**Pull request merged**
