### PR TITLE
add check for correct returnType of main

### PR DESCRIPTION
**Pull request by UplinkCoder**
This makes sure `main` can only `int` or `void`

### CODE REVIEW

**Comment by deadalnix** [comment]
There is already a check on the return type.

**Comment by deadalnix** [comment]
https://github.com/deadalnix/SDC/pull/94

Is that related to this ? If so, that is simply adding arbitrary limitations.

**Comment by UplinkCoder** [comment]
I guess returning anything else but an integer is non-sense.
http://en.wikipedia.org/wiki/Exit_status

**Comment by schancel** [comment]
@deadalnix AFAIK `int` is the only valid return type for `main`.   I don't know that we need a check for it, but can we either merge this or close it?

**Comment by UplinkCoder** [comment]
@schancel `int` and `void` are valid... void means `return 0;`

**Comment by deadalnix** [comment]
I see no reason to forbid anything that convert to int at the end and that can be achieved by adding a cast.

**Comment by schancel** [comment]
@UplinkCoder Yeah, but the OS actually expects a main with a signature of int.  That's what I mean.

@deadalnix Can you close this then?  No reason to leave PRs you aren't going to merge.

**Comment by deadalnix** [comment]
Well casting as int is still desirable.

**Comment by UplinkCoder** [comment]
@deadalnix pull please.
This returnType limitation is a sensible one.
We already type or `main` as returning int so we should enforce it in our `d_main` as well.

**Comment by schancel** [comment]
I'm kind of inclined to agree with UplinkCoder on this one.  POSIX is int or nothing.  And the error he prints is easy for people to grok(understand)

**Comment by deadalnix** [comment]
This is not a main function as it is in C. The correct think is to cast this result to int in the generated stub and error if it cannot be done implicitly.

**Pull request closed without merging**
